version: "3.4"
services:
  savsha:
    build: .
    image: savsha
    container_name: savsha
    volumes:
      - ".:/savsha"
      - ".data/root:/root"
    depends_on:
      - localhost
    ports:
      - "8080:8000"

  localhost:
    image: postgres:13.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456can
    container_name: savsha_postgres
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"