version: "3.4"
services:
  savsha:
    build: .
    image: savsha
    container_name: savsha
    volumes:
      - ".:/savsha"
      - ".data/root:/root"
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456can
    container_name: savsha_postgres
    volumes:
      - ".data/db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"