# Generated by Django 4.1.3 on 2022-11-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savsha', '0002_category_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('labels', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='')),
                ('space', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friends',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
