# Generated by Django 4.1.3 on 2022-12-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savsha', '0004_remove_contents_photo_remove_contents_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='first_name',
            field=models.CharField(default='previous', max_length=1000),
        ),
        migrations.AddField(
            model_name='contents',
            name='last_name',
            field=models.CharField(default='content', max_length=1000),
        ),
    ]
