# Generated by Django 4.1.3 on 2022-12-26 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('savsha', '0005_contents_first_name_contents_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='likes',
            field=models.ManyToManyField(related_name='contents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contents',
            name='first_name',
            field=models.CharField(default='previous ', max_length=1000),
        ),
    ]
