# Generated by Django 4.1.3 on 2022-12-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savsha', '0007_comments_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='first_name',
            field=models.CharField(default='name', max_length=1000),
        ),
        migrations.AddField(
            model_name='comments',
            name='last_name',
            field=models.CharField(default='surname', max_length=1000),
        ),
    ]
