# Generated by Django 4.1.3 on 2022-12-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savsha', '0008_comments_first_name_comments_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('picture', models.ImageField(null=True, upload_to='images')),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='contents',
            name='likes',
        ),
    ]
